#!/bin/sh /etc/rc.common
START=99

USE_PROCD=1
PROCD_DEBUG=1

load_conf() {
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local domain
		local ifname
		
		config_get username $1 username
		config_get password $1 password
		config_get domain $1 domain
		config_get ifname $1 ifname
		
		if [ "$domain" != "" ]; then
			procd_append_param command $username@$domain $password $ifname
		else
			procd_append_param command $username $password $ifname
		fi
	fi
}

service_triggers() { 
        procd_add_reload_trigger "login" 
        procd_add_interface_trigger "interface.*" "eth0" /etc/init.d/njitclient reload
}

start_service() {
    procd_open_instance
    procd_set_param command njit-client
	config_load njitclient
	config_foreach load_conf njitclient
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param file /etc/config/njitclient
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance

    echo "NJIT Client has started."
}

stop_service() {
	echo "NJIT Client has stoped."
}
